using SampleLibrary;
using NUnit.Framework;
using Moq;

namespace SampleLibrary.Tests
{
    class ClassBTests
    {
        private Mock<IDependency> _dependency;
        private Mock<IDependency> _dependency2;
        private ClassB _classB;
        [SetUp]
        public void Setup()
        {
            _dependency = new Mock<IDependency>();
            _dependency2 = new Mock<IDependency>();
            _classB = new ClassB(_dependency.Object, _dependency2.Object);
        }

        [Test]
        public void TestAction_Test()
        {
            _classB.TestAction();
            Assert.Fail("autogenerated");
        }
    }
}